### Login User Admin / PWD Admin
POST {{host}}/login
Authorization: Basic YWRtaW46YWRtaW4=

### Register User Admin / PWD Admin
PUT {{host}}/register
Content-Type: application/json

{
  "email": "admin",
  "password": "admin"
}


